name: $name
version: $version
main: io.github.shotoh.nonametags.NoNameTags
description: $description
load: STARTUP
authors:
  - shotoh
api-version: $apiVersion
commands:
    showname:
        description: "Reveals your nametag to someone"
        usage: "/showname (player)"
